services:
  - type: web
    name: fsuu-management
    env: docker
    rootDir: backend
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://fsuu-management.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: fsuu-management-mysql.render.com
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: fsuu_management
      - key: DB_USERNAME
        value: fsuu_user
      - key: DB_PASSWORD
        value: fsuu_password123
