services:
  - type: web
    name: fsuu-management-system
    env: docker
    rootDir: backend
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:XWHx8+c+7xCLI6MgECP0mRWQfCu9iDoIjVmwifcXmwA=
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://fsuu-management-system-1.onrender.com
      - key: FRONTEND_URL
        value: https://fsuu.vercel.app
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: db.aehkeidsmaqwoqprwpme.supabase.co
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        value: postgres
      - key: DB_PASSWORD
        value: Anonymous141
      - key: SANCTUM_STATEFUL_DOMAINS
        value: fsuu-management-system-1.onrender.com,fsuu.vercel.app
      - key: SESSION_DOMAIN
        value: fsuu-management-system-1.onrender.com
